In [3]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Define the companies we want to analyze 
tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'JPM', 'JNJ', 'WMT', 'XOM']

In [5]:
# Download financial data for all tickers
data = yf.download(tickers, period='1y')

[*********************100%***********************]  10 of 10 completed

In [11]:
data.tail()

Price            Close                                                  \
Ticker            AAPL        AMZN       GOOGL         JNJ         JPM
Date
2026-06-24  293.079987  234.270004  345.290009  241.000000  333.450012
2026-06-25  275.149994  227.009995  343.709991  244.880005  335.119995
2026-06-26  283.779999  232.690002  337.390015  254.660004  329.049988
2026-06-29  281.739990  240.139999  353.649994  258.510010  329.390015
2026-06-30  288.270203  238.929993  356.329987  256.209991  328.500000

Price                                                                   ...  \
Ticker            META        MSFT        TSLA         WMT         XOM  ...
Date                                                                    ...
2026-06-24  557.669983  365.459991  375.529999  119.000000  136.899994  ...
2026-06-25  542.869995  352.829987  375.119995  115.779999  137.550003  ...
2026-06-26  550.250000  372.970001  379.709991  115.690002  136.539993  ...
2026-06-29  562.599976  368.570007  411.839996  114.599998  136.059998  ...
2026-06-30  559.960022  370.940002  416.799988  113.680000  136.229996  ...

Price          Volume                                                      \
Ticker           AAPL       AMZN      GOOGL       JNJ       JPM      META
Date
2026-06-24   53081900   70282600   44997300   8139200   7907400  13963600
2026-06-25  107013700   77674100   44491400  10130400  10043100  16968600
2026-06-26  261775500  248372100  114706300  16316800  17640900  18867700
2026-06-29   66368400   77524800   34165800   8604700   7979400  14980900
2026-06-30   23087796   30221922   14030510   2448978   1913694   6907338

Price
Ticker           MSFT      TSLA       WMT       XOM
Date
2026-06-24   44509900  37081400  20600100  16212900
2026-06-25   66179000  30138800  20384700  13288800
2026-06-26  186201600  53434100  36636000  22684200
2026-06-29   51014000  57399800  20341900  11964800
2026-06-30   16990289  23623457   7348769   6114498

[5 rows x 50 columns]

In [12]:
data.shape

(252, 50)

In [14]:
companies = {}

for ticker in tickers:
    stock = yf.Ticker(ticker)
    companies[ticker] = stock.info

In [15]:
# Double check if code worked: load data for AAPL
companies['AAPL']

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1780531200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 281.74,
 'open': 281.17,
 'dayLow': 280.695,
 'dayHigh': 289.66,
 'regularMarketPreviousClose': 281.74,
 'regularMarketOpen': 281.17,
 'regularMarketDayLow': 280.695,
 'regularMarketDayHigh': 289.66,
 'dividendRate': 1.08,
 'dividendYield': 0.38,
 'exDividendDate': 1778457600,
 'payoutRatio': 0.1259,
 'fiveYearAvgDividendYield': 0.5,
 'beta': 1.086,
 'trailingPE': 34.98182,
 'forwardPE': 30.034594,
 'volume': 25150759,
 'regularMarketVolume': 25150514,
 'averageVolume': 52813456,
 'averageVolume10days': 79944460,
 'averageDailyVolume10Day': 79944460,
 'bid': 288.29,
 'ask': 290.98,
 'bidSize': 1,
 'askSize': 4,
 'marketCap': 4238770962432,
 'nonDilutedMarketCap': 4138015679440,
 'fiftyTwoWeekLow': 201.5,
 'fiftyTwoWeekHigh': 317.4,
 'allTimeHigh': 317.4,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.389403,
 'fiftyDayAverage': 291.8646,
 'twoHundredDayAverage': 269.7336,
 'trailingAnnualDividendRate': 1.04,
 'trailingAnnualDividendYield': 0.0036913466,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4154219560960,
 'profitMargins': 0.27152002,
 'floatShares': 14662534368,
 'sharesOutstanding': 14687356000,
 'sharesShort': 144248476,
 'sharesShortPriorMonth': 138782718,
 'sharesShortPreviousMonthDate': 1778803200,
 'dateShortInterest': 1781481600,
 'sharesPercentSharesOut': 0.0098,
 'heldPercentInsiders': 0.01632,
 'heldPercentInstitutions': 0.65827006,
 'shortRatio': 2.88,
 'shortPercentOfFloat': 0.0098,
 'impliedSharesOutstanding': 14687356000,
 'bookValue': 7.26,
 'priceToBook': 39.752068,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1774656000,
 'earningsQuarterlyGrowth': 0.194,
 'netIncomeToCommon': 122575003648,
 'trailingEps': 8.25,
 'forwardEps': 9.60892,
 'pegRatio': 2.29,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.202,
 'enterpriseToEbitda': 25.968,
 '52WeekChange': 0.3556924,
 'SandP52WeekChange': 0.20045471,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1778457600,
 'quoteType': 'EQUITY',
 'currentPrice': 288.6,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 315.09048,
 'targetMedianPrice': 315.0,
 'recommendationMean': 2.02128,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 42,
 'totalCash': 68507000832,
 'totalCashPerShare': 4.664,
 'ebitda': 159975997440,
 'totalDebt': 84710998016,
 'quickRatio': 0.906,
 'currentRatio': 1.07,
 'totalRevenue': 451442016256,
 'debtToEquity': 79.548,
 'revenuePerShare': 30.534,
 'returnOnAssets': 0.26229,
 'returnOnEquity': 1.4147099,
 'grossProfits': 216070995968,
 'freeCashflow': 101090746368,
 'operatingCashflow': 140222005248,
 'earningsGrowth': 0.218,
 'revenueGrowth': 0.166,
 'grossMargins': 0.47862,
 'ebitdaMargins': 0.35437,
 'operatingMargins': 0.32275,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'regularMarketTime': 1782843071,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 2.4348748,
 'regularMarketPrice': 288.6,
 'marketState': 'REGULAR',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'regularMarketChange': 6.860016,
 'regularMarketDayRange': '280.695 - 289.66',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 52813456,
 'fiftyTwoWeekLowChange': 87.100006,
 'fiftyTwoWeekLowChangePercent': 0.4322581,
 'fiftyTwoWeekRange': '201.5 - 317.4',
 'fiftyTwoWeekHighChange': -28.799988,
 'fiftyTwoWeekHighChangePercent': -0.0907372,
 'fiftyTwoWeekChangePercent': 35.569237,
 'dividendDate': 1778716800,
 'earningsTimestamp': 1777579200,
 'earningsTimestampStart': 1785441600,
 'earningsTimestampEnd': 1785441600,
 'earningsCallTimestampStart': 1777582800,
 'earningsCallTimestampEnd': 1777582800,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 8.25,
 'epsForward': 9.60892,
 'epsCurrentYear': 8.75456,
 'priceEpsCurrentYear': 32.965675,
 'fiftyDayAverageChange': -3.2645874,
 'fiftyDayAverageChangePercent': -0.011185281,
 'twoHundredDayAverageChange': 18.866394,
 'twoHundredDayAverageChangePercent': 0.069944546,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'displayName': 'Apple',
 'trailingPegRatio': 2.2765}

In [17]:
metrics = []

for ticker in tickers: 
    info = companies[ticker]
    metrics.append({
        'ticker': ticker,
        'company': info.get('shortName'),
        'sector': info.get('sector'),
        'employees': info.get('fullTimeEmployees'),
        'revenue': info.get('totalRevenue'),
        'profit_margin': info.get('profitMargins'),
        'operating_margin': info.get('operatingMargins'),
        'gross_margin': info.get('grossMargins'),
        'return_on_assets': info.get('returnOnAssets'),
        'revenue_per_share': info.get('revenuePerShare')
    })

In [19]:
df = pd.DataFrame(metrics) 
df

,ticker,company,sector,employees,revenue,profit_margin,operating_margin,gross_margin,return_on_assets,revenue_per_share
0,AAPL,Apple Inc.,Technology,166000,451442016256,0.27152,0.32275,0.47862,0.26229,30.534
1,MSFT,Microsoft Corporation,Technology,228000,318272995328,0.39342,0.46326,0.68309,0.14814,42.836
2,GOOGL,Alphabet Inc.,Communication Services,194668,422498009088,0.37919,0.36121,0.60368,0.14641,34.932
3,AMZN,"Amazon.com, Inc.",Consumer Cyclical,1575000,742775980032,0.12224,0.13140,0.50604,0.06845,69.477
4,META,"Meta Platforms, Inc.",Communication Services,77986,214962995200,0.32837,0.40617,0.81941,0.16395,85.210
5,TSLA,"Tesla, Inc.",Consumer Cyclical,134785,97878999040,0.03946,0.04203,0.19065,0.02233,30.312
6,JPM,JP Morgan Chase & Co.,Financial Services,320079,173559005184,0.33936,0.43741,0.00000,0.01272,63.096
7,JNJ,Johnson & Johnson,Healthcare,138200,96361996288,0.21834,0.27408,0.68035,0.08424,40.021
8,WMT,Walmart Inc.,Consumer Defensive,2100000,725304999936,0.03135,0.04215,0.24976,0.06835,90.976
9,XOM,Exxon Mobil Corporation,Energy,57900,326008012800,0.07765,0.06355,0.29768,0.04221,76.483